### ISSUE TITLE
Problems with running example code (01-compute-kinematics.py)

### ISSUE THREAD

**Issue by Xngzdai** [Kinovarobotics/kortex#112]
Hello!

I'm trying to retrieve the pose of the end effector to find the transformation from the camera frame to the world frame. When I ran `examples/111-kinematics/01-compute-kinematics.py` for a quick test without changing anything, it returned "Unable to compute forward kinematics" and "Unable to get current robot pose" to me, though it returned the joint angles. The error code for both of the issues are: `Error_code:1, Sub_error_code:5`.

I have confirmed that I'm connected to the arm properly. Is there any suggestions on fixing this? Thank you in advance!
Xingze

**Comment by felixmaisonneuve** [comment]
Hi @Xngzdai,

`Sub_error_code` is "UNSUPPORTED_METHOD", this ususally happens when your arm's firmware kit is Kortex2.2 but you are using the Kortex API 2.3. 
You call functions that do not exist for the arm.

To check your arm's firmware version, you can do it in the webapp in Systems->Upgrade (Firmware Bundle)
You can download the correct firmware kit with [this link](https://artifactory.kinovaapps.com/artifactory/generic-local-public/kortex/gen3/2.3.0/Gen3-2.3.0.swu) (which is also available on our [website](https://www.kinovarobotics.com/resources?r=79301))

Best,
Felix
