### ISSUE TITLE
Bug in C++ API Examples: 110-Waypoints

### ISSUE THREAD

**Issue by Y94Shen** [Kinovarobotics/kortex#135]
https://github.com/Kinovarobotics/kortex/blob/392c312d57912e9645c70cb3e783bdcdb89371bd/api_cpp/examples/110-Waypoints/01-send_angular_wapoint_trajectory.cpp#L163

Here I think `angleIndex` is supposed to be used instead of `index`
You happened to have 7 waypoints for the 7DOF Kinova Gen3, and this bug was not caught.
However, if I use another number, like 3 waypoints, sometimes the code would give me hard time saying:
`error_type: TRAJECTORY_ERROR_TYPE_INVALID_JOINT_SPEED`

Could you please check and confirm?

**Comment by felixmaisonneuve** [comment]
Hi @Y94Shen,

This is not a bug. 
This was added because in our 7 waypoints sequence, waypoints 4 and 6 need more movements from smalll actuators, which moves slower. Because of that, we increase the duration for that waypoint.

If you change your waypoints sequence, you have to change your duration accordingly. 5 seconds (`firstTime = 5.0f`) might not be enough for all of your joints to reach its position and you will end up with errors in your trajectory (e.g. `INVALID_JOINT_SPEED` where the actuator is trying to go faster then its limit)

I hope this makes sense, maybe I did not understand correctly.

Best,
Felix
