### ISSUE TITLE
read end-effector force

### ISSUE THREAD

**Issue by jzhu0909** [Kinovarobotics/kortex#63]
Hi, I have a question about how to read the end-effector force through API. According to the file in the api_cpp, I could read end-effector force through 'tool_external_wrench_force_x()'. But  the file also says I need to set the value of  'tool_external_wrench_force_x' through 'set_tool_external_wrench_force_x()' in advance, or the 'tool_external_wrench_force_x()' will return 0. I can't understand it, could you give me an example?

**Comment by felixmaisonneuve** [comment]
Hi @jzhu0909,

It is not possible to read the end-effector force. 

The `tool_external_wrench_force_x()` gives an approximation of the external force that is applied on the gripper, which must be set by the user (otherwise 0). It is not a measure of the force applied **by** the end-effector, but rather the force applied **on** the end-effector.

I will close this issue since it is not something supported, but feel free to reopen it if you still have questions or problems.

Regards,
Felix
