### ISSUE TITLE
Joint speed control is not accurate.

### ISSUE THREAD

**Issue by JDchen-Jaden** [Kinovarobotics/kortex#93]
Though I've asked the same questions in #90, I think opening up a new issue here is necessary. 
Our Gen3 has two problems now: 

1. **Speed control is not accurate anymore when send as a array.** 
> If I send speed command to a single actuator. The position is exactly as expeced.
- Spin 3rd joint only: speeds = {0.0f, 0.0f, -18.0f, 0.0f, 0.0f, 0.0f, 0.0f};
![image](https://user-images.githubusercontent.com/61251177/141835555-a639bbaf-cc3f-43d5-8e1f-23e4831fe174.png)
- Spin 4th joint only:= {0.0f, 0.0f, 0.0f, -6.0f, 0.0f, 0.0f, 0.0f};
![image](https://user-images.githubusercontent.com/61251177/141836004-fb6ed0c7-2047-45df-84b6-3e8e320c9b53.png)
- Spin 6th joint only: = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -4.0f, 0.0f};
![image](https://user-images.githubusercontent.com/61251177/141836189-d33659b1-c89d-482d-87ba-16596ec370c4.png)

> However, if I send a command to all actuators simultaneously like this: `speeds = {-14.0f, 18.0f, -18.0f -6.0f, 0.0f, -4.0f, 0.0f}`;  Gen3 cannot react appropriately to move to the desired position.

**Reuslt:**
![image](https://user-images.githubusercontent.com/61251177/141836830-013cad65-3652-47ba-ba77-cd502e1f6d11.png)
**Desired:** 
Position: {-70, 90, -90, -30, 0, -20, 0}

```
    if (actuator_count == 7)
    {
        //speeds = {-SPEED, 0.0f, SPEED, 0.0f, -SPEED, 0.0f, SPEED};
        speeds = {-14.0f, 18.0f, -18.0f -6.0f, 0.0f, -4.0f, 0.0f};
        for (size_t i = 0 ; i < speeds.size(); ++i)
        {
            auto joint_speed = joint_speeds.add_joint_speeds();
            joint_speed->set_joint_identifier(i);
            joint_speed->set_value(speeds.at(i));
            joint_speed->set_duration(1);
        }
        base->SendJointSpeedsCommand(joint_speeds);
        // Wait 5 seconds
        std::this_thread::sleep_for(std::chrono::milliseconds(5000));
 ``` 
2. **Robot does not respond to velocity command in low-level control.**
In example [https://github.com/Kinovarobotics/kortex/tree/master/api_cpp/examples/200-Actuator_low_level_control](url), If I modified the following code 
```
commands[i] += (0.001f * velocity);
base_command.mutable_actuators(i)->set_position(fmod(commands[i], 360.0f));
```
to be 
```  
commands[i] = velocity;
base_command.mutable_actuators(i)->set_velocity(commands[i]);
``` 

The robot does not react (no movement) to this command. However, in #42, other user observed drift which means the robot at least reacted to the command. Our modification is exactly the same. I have no idea why it does not work for us.

**Comment by felixmaisonneuve** [comment]
1. I have tested it and experienced the same issue. I will investigate this and get back to you when I have a solution. Thank you to have noticed that, I am not sure what is happening. 
2. I have answered that in the other issue, but I am pretty sure your actuator is still in POSITION ControlMode. You need to change it with `actuatorConfig->setControlMode(controlModeInfo)`

**Comment by felixmaisonneuve** [comment]
So basically you are missing a coma 
```c++
speeds = {-14.0f, 18.0f, -18.0f, -6.0f, 0.0f, -4.0f, 0.0f};
```
instead of 
```c++
speeds = {-14.0f, 18.0f, -18.0f -6.0f, 0.0f, -4.0f, 0.0f};
```

**Comment by JDchen-Jaden** [comment]
Hi! @felixmaisonneuve 

.....................................................................................................................................................................................................
First, I would like to express my thankfulness for all your help. Thank you very much for answering all questions quickly and patiently. I am struggling to understand and use the API due to my limited programming background. Thank you for being understanding and responsible!
.....................................................................................................................................................................................................

1, Oh, No... I am so sorry for any inconvenience this brought to you! 

2, I finally found the example of using `setControlMode ` in the torque control example. (This function call does not appear in the example of low-level velocity control, adding this function here would be helpful for other users who will never check out the torque control). The following are some issues I am struggling with: 
-  In #90 (Question (3)), `Refresh()` works well and will send command to all actuators if ignore the `uint32_t deviceId = 0` argument or set is to be 0 as default in. However, when I repeat the same procedure when calling `SetControlMode(control_mode_message)` or `SetControlMode(control_mode_message, 0)`, an error appears as follows:
```
Kortex error: Server protocol error, Error sub type=UNSUPPORTED_SERVICE => <srv: 10, fct: 7, msgType: 3>
description: Service not registered for service id: 10
```
To this end, do I have to set a control mode for each actuator as follows? 
```
actuator_config->SetControlMode(control_mode_message,1);
actuator_config->SetControlMode(control_mode_message,2);
.
.
.
actuator_config->SetControlMode(control_mode_message,7);
```

- If I specify an actuator, e.g. fist actuator: ` SetControlMode(control_mode_message, 1)`. The robot can move and no drift was observed. However, the robot stops after  2 s movement (which is supposed to be 5 s in the example). And the following error appears:
```
[libprotobuf FATAL /home/jd-vmware/.conan/data/kortex_api_cpp/2.3.0-r.34/kortex/stable/package/9755f981ac44041fa0948f05e49abfa3d3346131/thirdParty/include/google/protobuf/repeated_field.h:1521] CHECK failed: (index) >= (0): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) >= (0): 
```

**Comment by felixmaisonneuve** [comment]
Yes, you have to specify ControlMode for each joint. 
`SetControlMode(control_mode_message)` and `SetControlMode(control_mode_message, 0)` does not work because `0` is the base, and you cannot change ControlMode for the base since it is not an actuator. It simply doesn't have control modes.

The drift observed in the other issue was caused by gravity in VELOCITY ControlMode. Gravity does not affect joint 1 (because of its orientation). 

Based on the error message, you have a RepeatedField index `<0`. RepeatedFields are protobuf's "array" system (sort of). In your base command (`base_command.mutable_actuators(0)`), your `mutable_actuators` are a repeated field. You might be trying to access a value with a negative index or sending a base_command without any `mutable_actuators`, it might be another repeated field.... It is hard to tell without any code. 

Since it happens after 2s, I would try to look at what happens if your base_commands are sent too fast or too slow.

**Comment by JDchen-Jaden** [comment]
The code simply adds `SetControlMode` based on the example [https://github.com/Kinovarobotics/kortex/tree/master/api_cpp/examples/200-Actuator_low_level_control](url)

Please refer to the code here: https://github.com/JDchen-Jaden/Gen3_test/blob/main/00-actuator_low_level_velocity_control.cpp

**Comment by JDchen-Jaden** [comment]
Hi @felixmaisonneuve 

I ran into two different types of issues when using low-level velocity control (same code). I have no idea if these issues share the same reason as the above issue. 

The following is the simple structure of my code. Also, could you please suggest why the same code throw different errors? Thank you! 
```
main () {
    servoingMode.set_servoing_mode(k_api::Base::ServoingMode::LOW_LEVEL_SERVOING);

        auto control_mode_message = k_api::ActuatorConfig::ControlModeInformation();
        control_mode_message.set_control_mode(k_api::ActuatorConfig::ControlMode::VELOCITY);
        auto actuator_config = new k_api::ActuatorConfig::ActuatorConfigClient(router);
        actuator_config->SetControlMode(control_mode_message,1);
        actuator_config->SetControlMode(control_mode_message,4);
        actuator_config->SetControlMode(control_mode_message,6); 
    while(1) 
    {
        for(int i = 0; i < actuator_count; i++)
        {
            base_command.mutable_actuators(i)->set_velocity(q_dot_command(i));
        }
        feedback = base_cyclic->Refresh(base_command,0);
    }
    servoingMode.set_servoing_mode(k_api::Base::ServoingMode::SINGLE_LEVEL_SERVOING);
    base->SetServoingMode(servoingMode);
} 
```

- **ISSUE 1**: The robot stop moving in a few seconds. Then an error appeared as follows. The `ServoingMode ` can only change to be `SINGLE_LEVEL_SERVOING` when the `while` loop is finished. However, I have an infinite while loop as you may notice in the above code. Why did the servoing mode change? 
```
terminate called after throwing an instance of 'Kinova::Api::KDetailedException'
  what():  Device error, Error sub type=WRONG_SERVOING_MODE => <srv: 3, fct: 1, msgType: 3>
description: Wrong servoing mode, must be low level servoing mode
Aborted (core dumped)
```
![image](https://user-images.githubusercontent.com/61251177/142256315-0ad1e7b4-bf1e-4e13-a1a9-4a9a568bedc0.png)
![image](https://user-images.githubusercontent.com/61251177/142256384-ea1df012-474c-4bb6-a690-53cf260a6f6b.png)

- **ISSUE 2**: No errors appear in the terminal. But the robot stop after around 2 s movement. The errors for three velocity-controlled joints are the same: Following Error.

![image](https://user-images.githubusercontent.com/61251177/142253056-81740da7-6991-4c7a-ab17-6e8fa4c91ef6.png)
![image](https://user-images.githubusercontent.com/61251177/142253149-778ffc3f-47fb-4c08-858a-b9dd223f600d.png)

**Comment by felixmaisonneuve** [comment]
1. That's because you never actually change the servoing mode, or at least it is not in the code you shared.
```C++
base->SetServoingMode(servoingMode);
```

2. Following errors happen when a joint is unable to reach the requested position/velocity (I think). The point is they are very frequent and there is a huge amount of reason why one could be triggered. Before using the arm again,you need to `clearFaults()`. You can do this either in your code at the beginning (like in the Torque example) or manually in the webapp. 
For this second issue, if the arm always fail at the same time, it might be one of your command that is wrong. At some point you might ask your arm to go too fast or something. It is also possible your joints receive an old command message that took more time before reaching the joint. The torque control example already has logic to set a `frame_id` to each command so that previous commands are ignored. 
Finally, notice that each call to the API is always in a try/catch. I would suggest you to do the same. A call can fail for multiple reason, this will give you details on what is the error and it won't crash your whole program. 

I understand you do not have a programming background, but you are now asking me to debug code rather then asking how to use the API. We provide plenty of examples that cover 95% of what you are trying to do. Take your time to analyse all of them and fully understand what they do and how they do it. 
Also, you should start from one of these (that we know work) and do small changes instead of just writing your own code from A to Z. It will be a lot easier for you to pin point what is wrong if something doesn't work. 

Regards,
Felix

**Comment by JDchen-Jaden** [comment]
Hi @felixmaisonneuve 

Before getting into the specific issues I posted. Firstly, I wish to sincerely express my thankfulness for all your patient help. Your response is always quick and provides helpful suggestions. Secondly, I wish to declare some miscommunication here. My original goal is not to ask you to help me to debug. If you double-check my question you may see my question was that **the velocity control did not work properly though I strictly follow the steps you suggested**. The code is pretty simple, I did simply change the control mode and sent the velocity command. However, it does not work as it should be. I believe this is something that I could not find on Github. 

Yes, I do have limited programming skills. And I did post many questions recently. But I believe all questions I asked on Github are all tightly related to my confusion about how to use API. I really appreciate that you patiently helped me to check the mistake I made on the "comma" in the velocity command, and I feel sorry for the inconvenience that it brought to you. Other than that, I tried my best to learn the code by running and modifying it before posting an issue. Though I checked everything I know, like .h files, markdown files, and the old issues on Github, I still have trouble understanding some commands. If the user could not find more useful details on Github, it is reasonable to ask questions. 

My experience is that asking questions on Github is WAY efficient than Kinova Support email because of you. If you don't think this is an API-related problem to be posted here, please let me know. 

If you think we are cool with the miscommunication, the following are my questions: 

1, I did change the serving mode. The example is here https://github.com/JDchen-Jaden/Gen3_test/blob/main/00-actuator_low_level_velocity_control.cpp . For your convenience, the modifications are lines 182-185, 212, 315;  If the velocity control works properly, there should be no errors. So my problem is that the velocity control does not work properly on our Gen3.

2, I will carefully learn all info you shared with me. Thank you very much. Also, thank you so much for the insightful suggestions for learning this API.

**Comment by JDchen-Jaden** [comment]
Including `base_command.mutable_actuators(i)->set_position(base_feedback.actuators(i).position());` right above `base_command.mutable_actuators(i)->set_velocity(commands[i]);` and setting up first frame solved the problem. 

However, I am a bit confused about the usefulness of `set_position` before  `set_velocity` since the control mode has been set in VELOCITY for a specific actuator. What is going to happen if you execute `set_position` for the same actuator? 

Thanks!

**Comment by felixmaisonneuve** [comment]
Thank you for the great comments. I just wanted to make sure you are actually trying to understand rather then asking for every error message that comes up. As long as you do your part, I will do mine. I have absolutely no problem answering all the questions you have if it helps you, and I will keep doing it. 

Now, we often receives complaints about the VELOCITY ControlMode, because of the "drift" issue. I think it doesn't apply here and you should be able to make it work. Looking at your example, your code looks good. I don't see anything unusual ecept that you set joint 7 to POSITION mode instead of joint 1, but that is not related.
https://github.com/JDchen-Jaden/Gen3_test/blob/4782391b15b9123da96218c4abaaea6cbda164a3/00-actuator_low_level_velocity_control.cpp#L229-L230

Do you know if both errors happen when your code is running in the while loop? I see in your code there is a couple of `cout` that can help us find where the errors are coming from. What are all the printed statements in your terminal?

When you say the velocity ControlMode is not working, do you mean the arm is not moving at all, or it is rotating before crashing? If the joint is not moving at all, I would try manually adding an acceleration. The joint can go at 5 degrees/s, but it cannot go from 0 to 5 in 1ms. I don't know if the actuator does this on its own or if you have to manually set an acceleration. 

Also, I would remove/comment the print statements in your callback function. You can leave your callback empty for now. I think this could slow considerably your loop and might generate weird errors. I don't know if it is the case here, but I would remove them just to be safe. 

The usefulness of having `position`, `velocity` and `torque` is because it allows us to have the same command for all the different control modes. Values will simply be ignored if they are not required. ControlModes can also take different combinaisons of these 3. For example, POSITION ControlMode will look at all three values, but I am not sure how they process them. One thing I know is that `position` will be reached regardless of `velocity` and `torque` in POSITION control mode.

**Comment by JDchen-Jaden** [comment]
Hi @felixmaisonneuve 

Thanks! I got your point. I am thankful that you would like to help answer questions. Again, thank you so much for always responding quickly. 

My arm rotates a bit before crashing. The above modification solved the problem. I just need to spend some time to understand why it works out. 

Thanks for sharing the functionality of ControlMode with me. I think it is helpful for me to understand the API more. Thanks again!

**Comment by felixmaisonneuve** [comment]
If you are talking about the print statements (that solved the issue), my guess is printing stuff in the console output slows your execution time (quite considerably because we are talking about one line every ms). At some point, when there is a lot to write in the console, your program is not able to keep up and send a message every ms. This will probably cause an error of some sort for whatever reason (since the base/actuator is expecting a message every ms but doesn't get it). 

It is important to keep your loop cycle time under or close to the ms and send a new command in each cycle, to avoid creating errors like that. I do not know exactly what is happening, but I am pretty sure the slow cycle time (caused by the multiple print statements) is the issue here.

**Comment by JDchen-Jaden** [comment]
Oh, I see. I did not make it clear. 

I did not comment out the print statements. What you suggested is important. And I'll try to avoid any print commands in a loop in future tests. 

The following steps are what I tried. And It gets the problem (actuator crash after a short period of movement)  resolved. After these modifications, the joint can be controlled by velocity command without crashing. I still need to learn why it works out. 
- I set up the first frame: `base_feedback = base_cyclic->Refresh(base_command);`
-  I added `base_command.mutable_actuators(i)->set_position(base_feedback.actuators(i).position());` right above `base_command.mutable_actuators(i)->set_velocity(commands[i]);` 
- Instead of calling `base_feedback = base_cyclic->Refresh(base_command, 0);` immediately, I referred to the <torque example> to set `frame_id` and `command_id` first, then call `base_cyclic->Refresh(base_command, 0)`.
